language: node_js
env:
  global:
    - GH_USER: nelson
    - DEPLOY_ENV: GH_PAGES
node_js:
  - "7.0.0"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - develop

install:
  - travis_retry npm i -g yarn 
  - travis_retry yarn global add gulp bower 
  - travis_retry yarn
  - gulp build

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: develop
